services:
  postgres:
    image: postgres:16
    container_name: ai-chat-mod-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_chat_mod
    ports:
      - 5132:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:4.0.1
    hostname: broker
    container_name: ai-chat-mod-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  redis:
    image: redis:7
    container_name: ai-chat-mod-redis
    restart: always
    ports:
      - 6793:6379
    volumes:
      - redis:/data
    command: ["redis-server", "--appendonly", "yes"]

  backend:
    build:
      dockerfile: dockerfile
    container_name: ai-chat-mod-backend
    depends_on:
      - postgres
      - kafka
      - redis
    network_mode: host
    ports:
      - 8000:8000

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ai-chat-mod-cloudflare-tunnel
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiMDRiMmY4NDE0M2IyYWQxN2YzNjhhNDg2M2QyNjA5NmEiLCJ0IjoiZjJkMzhkMjEtNDQyMi00YWZmLTk0OGYtNDc2NmU3OWE5NmFlIiwicyI6IllXRmlNalUyTUdRdE5ERXhNQzAwTkRNNExXRmpZVE10TldNMk5tWTVOMk0wTW1ObSJ9

volumes:
  postgres:
  redis:
